### ISSUE TITLE
Links with ampersand signal in "Full Name" column seem broken

### ISSUE THREAD

**Issue by fnery** [markramrattan/freetrade-universe-web#2]
It seems that the ampersand (`&`) character isn't correctly escaped when clicking links in the `FULL NAME` column from stocks containing `&` in their name.

For example, click the McCormick & Co. and AT&T links (blue arrows in the next figure):

![image](https://user-images.githubusercontent.com/3774685/84689404-d4b6ca80-af38-11ea-8f44-018a3f103b34.png)

The following are the resulting tabs (on chrome) from clicking the links.

![image](https://user-images.githubusercontent.com/3774685/84689218-8bff1180-af38-11ea-8aeb-d7714c7f23b5.png)
![image](https://user-images.githubusercontent.com/3774685/84689208-8a354e00-af38-11ea-8406-08de26d7d77f.png)

Perhaps generating the search link using a combination of the `MIC` and `SYMBOL` columns could help?

For example, for McCormick & Co. searching google for NYSE:MKC takes me to the correct google finance page ([link](https://www.google.com/search?q=NYSE:MKC)). Note here I had to replace the actual `MIC`, which is `XNYS` by the exchange acronym `NYSE`.

P.S. Great work with this! 👍

**Comment by markramrattan** [comment]
That is definitely a better way to do it, i'll update it with that pattern. Thank you!
